services:
  # A Docker web service
  - type: web
    name: api-stock-predict
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r ./api/requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT